In [ ]:
#1.1 Write a program to count the number of characters in the string and store them in a dictionary data structure.

s=input("enter a string : ")
d={}
for i in s :
  if i in d:
    d[i] += 1
  else:
    d[i] = 1
print(d)

enter a string : BHKJMhgv
{'B': 1, 'H': 1, 'K': 1, 'J': 1, 'M': 1, 'h': 1, 'g': 1, 'v': 1}


In [ ]:
s=input("enter a string : ")
d={}
for i in s :
  d[i]=s.count(i)
print(d)

enter a string : gfdtujigg
{'g': 3, 'f': 1, 'd': 1, 't': 1, 'u': 1, 'j': 1, 'i': 1}


In [ ]:
#1.2 write a program to use split and join methods in the string and trace a birthday with dictionary data structure.

s = input("Enter a date in the format DD.MM.YYYY : ")
c = s.split(".")
b = ("/".join(c))
print("The date is : ",b)

Enter a date in the format DD.MM.YYYY : 10.08.2022
The date is :  10/08/2022


In [ ]:
#2. Write a program to perform various operations on matrices.

import numpy as np
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
B = np.array([[3,1,5],[-6,3,4],[1,8,2]])
print("A=\n",A)
print("B=\n",B)
add = np.add(A,B)
print("Addition=\n",add)
sub1 = np.subtract(A,B)
print("Subtraction1=\n",sub1)
sub2 = np.subtract(B,A)
print("Subtraction2=\n",sub2)
mul = np.multiply(A,B)
print("Multiplication=\n",mul)
div = np.divide(A,B)
print("Division=\n",div)
mod = np.mod(A,B)
print("Modulus=\n",mod)
transpose_A = np.transpose(A)
print("Transpose_A=\n",transpose_A)
transpose_B = np.transpose(B)
print("Transpose_B=\n",transpose_B)

A=
 [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
B=
 [[ 3  1  5]
 [-6  3  4]
 [ 1  8  2]]
Addition=
 [[ 5  2  2]
 [-9 -3  5]
 [ 2  9  3]]
Subtraction1=
 [[-1  0 -8]
 [ 3 -9 -3]
 [ 0 -7 -1]]
Subtraction2=
 [[ 1  0  8]
 [-3  9  3]
 [ 0  7  1]]
Multiplication=
 [[  6   1 -15]
 [ 18 -18   4]
 [  1   8   2]]
Division=
 [[ 0.66666667  1.         -0.6       ]
 [ 0.5        -2.          0.25      ]
 [ 1.          0.125       0.5       ]]
Modulus=
 [[ 2  0  2]
 [-3  0  1]
 [ 0  1  1]]
Transpose_A=
 [[ 2 -3  1]
 [ 1 -6  1]
 [-3  1  1]]
Transpose_B=
 [[ 3 -6  1]
 [ 1  3  8]
 [ 5  4  2]]


In [ ]:
#3. Write a function to find mean, median, mode for the given set of numbers in a list.

import statistics as s
L = [1,2,3,4,5,6,7,8,4,4,4]
x=s.mean(L)
y=s.median(L)
z=s.mode(L)
print("mean:",x)
print("median:",y)
print("mode:",z)

mean: 4.363636363636363
median: 4
mode: 4


In [ ]:
#4. Write a function nearly_equal to test whether two strings are nearly equal. 
#Two strings a and b are nearly equal when a can be generated by a single mutation on b.

def nearly_equal(str1,str2):
  count=0
  i=j=0
  while(i<len(str1) and j<len(str2)):
    if(str1[i]!=str2[j]):
      count=count+1
      if(len(str1)>len(str2)):
        i=i+1
      elif(len(str1)==len(str2)):
        pass
      else:
        i=i-1
    if(count>1):
      return False
    i=i+1
    j=j+1
  if(count<2):
    return True
str1=input("enter first string::\n" )
str2=input("enter second string::\n")
boolean=nearly_equal(str1,str2)
if(boolean):
  print("strings are nearly equal.")
else:
  print("strings are not equal.")

enter first string::
rise
enter second string::
risee
strings are nearly equal.


In [ ]:
#5. Demonstrate Basic date and time classes, Different time formats, Converting between formats, 
#Formatting dates and times, Parsing date/time information.

import datetime

datetime_=datetime.datetime.now()
print("Current date and time is : ",datetime_)

In [ ]:
#6. Create a class ATM and define ATM operations to create account, deposit, check_balance, withdraw and delete account. 
#Use constructor to initialize members.

class bankaccount :
  
  def __init__(self):
    self.balance=0

  def deposit(self):
    a=(int(input("Enter the amount to be deposited : ")))
    self.balance+=a
    print("Amount deposited : ",a)

  def withdraw(self):
    x=int(input("How much amount you want to withdraw ? :"))
    if self.balance<x:
      print("Insufficient balance in account")
    else :
      self.balance=self.balance-x
      print("Final balance = ",self.balance)

balance=bankaccount()
balance.deposit()
balance.withdraw()

Enter the amount to be deposited : 20000
Amount deposited :  20000
How much amount you want to withdraw ? :3000
Final balance =  17000


In [ ]:
#7. Make a class Employee with a name and salary. Make a class Manager inherit from Employee. 
#Add an instance variable, named department. Write a method that prints manager's name, department and salary. 
#Make a class Executive inherit from Manager.
#Write a method that prints the string "Executive" followed by the information stored in the Manager super class object.

class Employee :
  def __init__(self,name,salary) :
    self.name = name
    self.salary = salary
class Manager(Employee) : 
  def __init__(self,department) :
    self.department = department

  def print_info(self) :
    print("Name : ",self.name)
    print("Salary : ",self.salary)
    print("Department : ",self.department)

class Executive(Manager) : 
  def __init__(self) :
    print("Executive")
    
obj=Executive()
obj.name = input("Enter name of the employee : ")
obj.salary=int(input("Enter salary of the employee : "))
obj.department=input("Enter department : ")
obj.print_info()

Executive
Enter name of the employee : mark
Enter salary of the employee : 5000000
Enter department : plastics
Name :  mark
Salary :  5000000
Department :  plastics


In [ ]:
#8. Read two numbers n1 and n2. Write a function to compute n1/n2 and use try/except to catch the exceptions.

def compute (n1,n2):
  try : 
    div = n1/n2
    print(n1,"/",n2,"=",div)
    
  except ZeroDivisionError: 
    print(n1,"/",n2,"= Sorry! you are dividing by 0")
  except TypeError:
    print(n1,"/",n2,"Sorry! Character not allowed")

compute(20,2)
compute(3,0)
compute("a",3)

20 / 2 = 10.0
3 / 0 = Sorry! you are dividing by 0
a / 3 Sorry! Character not allowed


In [ ]:
#9. Write a Python program to detect and handle the exception while solving the quadratic equation.

from math import sqrt
print ("Quadratic equation is in the form :  a*x**2 + b*x + c = 0.")

done = False

while not done : 
  try:
    a = int(input("Enter value of a : "))
    b = float(input("Enter value of b : "))
    c = float(input("Enter value of c : "))
    d = b**2 - 4*a*c
    sq = sqrt(d)
    root1 = (-b - sq)/(2*a)
    root2 = (-b + sq)/(2*a)
    print("First root : ", root1)
    print("Second root : ", root2)
    done = True 

  except ValueError : 
    print("Value error, wrong equation. Try again.")

  except ZeroDivisionError :
    print("Zero division error, 'a' can't be 0. Try again.")

Quadratic equation is in the form :  a*x**2 + b*x + c = 0.
Enter value of a : 1
Enter value of b : 2
Enter value of c : 3
Value error, wrong equation. Try again.
Enter value of a : 0
Enter value of b : 3
Enter value of c : -7
Zero division error, 'a' can't be 0. Try again.
Enter value of a : 1
Enter value of b : -3
Enter value of c : -7
First root :  -1.5413812651491097
Second root :  4.541381265149109


In [ ]:
#10. Write a Python program to handle the run time errors while doing file handling operation.

try :
  with open('example.txt' ,'r')as file1:
    f=file1.read()
    print(f)

  with open('example.txt' ,'w')as file1:
    f=file1.write("hey")

  with open('example.txt' ,'a')as file1:
    file1.write("abc")

except FileNotFoundError :
  print("No such file exist")

No such file exist


In [1]:
#11. Write a python program to perform various database operations (create, insert, delete, update).

import sqlite3
import pandas 
db = sqlite3.connect("emp1.db")
db.execute("Drop table if exists employee")
db.execute("CREATE TABLE employee(ID text, Name text, Gender text, Address text, Date_of_joining text)")
db.execute("INSERT INTO employee(ID, Name, Gender, Address, Date_of_joining)VALUES(12,'Meredith','F','SE','24/02/2003')")
db.execute("INSERT INTO employee(ID, Name, Gender, Address, Date_of_joining)VALUES(34,'George','M','LA','04/03/2008')")
db.execute("INSERT INTO employee(ID, Name, Gender, Address, Date_of_joining)VALUES(56,'Izzie','F','NY','22/02/2010')")
db.execute("INSERT INTO employee(ID, Name, Gender, Address, Date_of_joining)VALUES(78,'Alex','M','LV','17/08/2015')")
db.execute("INSERT INTO employee(ID, Name, Gender, Address, Date_of_joining)VALUES(90,'Cristina','F','SF','25/05/2020')")
db.commit()
table = pandas.read_sql_query(''' SELECT *FROM employee ''', db)
table.head()

ID      Name Gender Address Date_of_joining
0  12  Meredith      F      SE      24/02/2003
1  34    George      M      LA      04/03/2008
2  56     Izzie      F      NY      22/02/2010
3  78      Alex      M      LV      17/08/2015
4  90  Cristina      F      SF      25/05/2020

In [ ]:
#12. Design a Python GUI application that pops up a message window when clicked on the button.

''' from tkinter import *
import tkinter.messagebox
root=Tk()
label=Label(text="When you press the button, a message will pop up")
label.pack()
def OnClick():
    tkinter.messagebox.showinfo("Have a great day!")
button=Button(root,text="click",command=OnClick,height=5,width=10)
button.pack()
 '''

' from tkinter import *\nimport tkinter.messagebox\nroot=Tk()\nlabel=Label(text="When you press the button, a message will pop up")\nlabel.pack()\ndef OnClick():\n    tkinter.messagebox.showinfo("Have a great day!")\nbutton=Button(root,text="click",command=OnClick,height=5,width=10)\nbutton.pack()\n '