In [1]:
#perform opeations on matrix

import numpy as np
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
B = np.array([[3,1,5],[-6,3,4],[1,8,2]])
print("A=\n",A)
print("B=\n",B)
add = np.add(A,B)
print("Addition=\n",add)
sub1 = np.subtract(A,B)
print("Subtraction1=\n",sub1)
sub2 = np.subtract(B,A)
print("Subtraction2=\n",sub2)
mul = np.multiply(A,B)
print("Multiplication=\n",mul)
div = np.divide(A,B)
print("Division=\n",div)
mod = np.mod(A,B)
print("Modulus=\n",mod)
transpose_A = np.transpose(A)
print("Transpose_A=\n",transpose_A)
transpose_B = np.transpose(B)
print("Transpose_B=\n",transpose_B)

A=
 [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
B=
 [[ 3  1  5]
 [-6  3  4]
 [ 1  8  2]]
Addition=
 [[ 5  2  2]
 [-9 -3  5]
 [ 2  9  3]]
Subtraction1=
 [[-1  0 -8]
 [ 3 -9 -3]
 [ 0 -7 -1]]
Subtraction2=
 [[ 1  0  8]
 [-3  9  3]
 [ 0  7  1]]
Multiplication=
 [[  6   1 -15]
 [ 18 -18   4]
 [  1   8   2]]
Division=
 [[ 0.66666667  1.         -0.6       ]
 [ 0.5        -2.          0.25      ]
 [ 1.          0.125       0.5       ]]
Modulus=
 [[ 2  0  2]
 [-3  0  1]
 [ 0  1  1]]
Transpose_A=
 [[ 2 -3  1]
 [ 1 -6  1]
 [-3  1  1]]
Transpose_B=
 [[ 3 -6  1]
 [ 1  3  8]
 [ 5  4  2]]
